version: "3"
services:
  web:
    build: .
    depends_on:
      - mysql
      - mailhog
    ports:
      - "9080:80"
    volumes:
      - ./laravel.projet-mOvie:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      - MYSQL_DATABASE=db_docker
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_ROOT_PASSWORD=root
  adminer:
    image: adminer:4.8.1
    depends_on:
      - mysql
    ports:
      - "9081:8080"
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "9082:8025"
